# -*- encoding : utf-8 -*-
## YAML Template
production:
  adapter: mysql2
  username: root
  host: localhost
  encoding: utf8
  database: jianzi

development:
  adapter: mysql2
  username: root
  password: root
  host: localhost
  encoding: utf8
  database: shuhua
